---
title: "SOLAL"
author: "Lucile Solal"
format: html
---

# Question 1
```{r}
here::i_am("SOLAL.Rproj")
library(here)
library(readr)
data <- read.csv(here("grades.csv"))
```

# Question 2
The data set contains `r NROW(data)` grades. 

# Question 3
```{r}
library(dplyr)
nb_students <- data |>
  distinct(id)
```
The data set contains `r NROW(nb_students)` students 

# Question 4
```{r}
students <- data |>
  distinct(id, .keep_all = TRUE) |>
  summarise(id, group)

students |>
  slice_tail(n = 10) |>
  knitr::kable()
```

# Question 5
```{r}
library(ggplot2)
ggplot(students, aes(x=group)) +
  geom_bar()
```

# Question 6
```{r}
average <- data |>
  filter(course == "Airship Piloting and Navigation") |>
  group_by(group) |>
  summarise(average = mean(grade))

ggplot(average, aes(x = group, y = average)) +
  geom_col()
```

# Question 7
```{r}
ggplot(data, aes(x = grade, fill = module)) + 
  geom_density()
```

# Question 8
```{r}
grades_per_student <- data |> 
  group_by(id, group) |>
  summarise(nb_grades = n())

grades_per_student |>
  slice(1:10)

summary <- grades_per_student |>
  summarise(minimum = min(nb_grades), 
            maximum = max(nb_grades), 
            average = mean(nb_grades), 
            median = median(nb_grades))

summary(grades_per_student)
```
Minimum: `r min(summary$minimum)`
Maximum: `r max(summary$maximum)`
Average: `r mean(summary$average)`
Median: `r median(summary$median)`

# Question 9
```{r}
crypto_nb_grades <- data |>
  filter(course == "Cryptography and Codebreaking") |>
  group_by(id, group) |>
  summarise(nb_grades = n())

crypto_nb_grades |>
  slice(1:10)
```
# Question 10
```{r}
distrib_crypto <- crypto_nb_grades |>
  group_by(nb_grades) |>
  summarise(student_distrib = n())

ggplot(distrib_crypto, aes(x=nb_grades, y = student_distrib)) +
  geom_col()
```

